<?php

namespace GSPEM\GSPEMBundle\Repository;

/**
 * AltaStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AltaStockRepository extends \Doctrine\ORM\EntityRepository
{
}
