GSPEM\GSPEMBundle\Entity\StockTecnico:
    type: entity
    table: stock_tecnico
    repositoryClass: GSPEM\GSPEMBundle\Repository\StockTecnicoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
            material:
                type: integer
            tecnico:
                type: integer
            cant:
                type: integer
    lifecycleCallbacks: {  }