<?php

namespace KarcherBundle\Repository;

/**
 * DistribuidorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistribuidorRepository extends \Doctrine\ORM\EntityRepository
{
}
