<?php

namespace KarcherBundle\Repository;

/**
 * EstadoOrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoOrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
