<?php

namespace KarcherBundle\Repository;

/**
 * LogOrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogOrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
