<?php

namespace KarcherBundle\Repository;

/**
 * MaterialOrigenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialOrigenRepository extends \Doctrine\ORM\EntityRepository
{
}
