<?php

namespace KarcherBundle\Repository;

/**
 * TipoOrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoOrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
